# alertmanager.yml
route:
  receiver: 'Mail Alert'
  # group_by: [ alertname ]
  repeat_interval: 30s
  group_wait: 15s
  group_interval: 15s

receivers:
  - name: 'Mail Alert'
    email_configs:
      - smarthost: 'mailcatcher.local:1025'
        auth_username: 'username'
        auth_password: "IWontTellyou"
        from: 'mom@friendly-robots.org'
        to: 'leela@planet-express.biz'
        headers:
          subject: 'Prometheus Mail Alerts'