= FastAPI - One Stop Shop

We will be building a full blown REST API based on FastAPI.
We'll start with a simple API and then add more features to it.
This will be a simple API that will allow us to create, read, update and delete data on ships from the Startrek universe.

Everything will be done in devcontainers. So you can run the code in a container without having to install anything on your local machine - except Docker Desktop.

== Branching

I'll split the implementation into multiple parts. Each part in its own branch - so you can skip any part you don't want to see.
The branches will be named after the part they represent.
The branches are:

- `phase-0`: Basic FastAPI app with all dependencies, a simple GET endpoint and test code. A Makefile is included to show how to run the tests and stuff. A Pipeline is included to run the tests on every commit. Coverage reports are generated and published to https://cwacoderwithattitude.github.io/articles_dc_fastapi_startrek/[github pages].
- `crud`: Add a simple CRUD API to the app. This will allow us to create, read, update and delete data on ships from the Startrek universe. The data will be stored in a SQLite database. Our test coverage enables us to refactor our code without any doubt on correct functionality.
    * replaced sqlite with a PostgreSQL db.
    * added DB Adminer to provide a used friendly interface to the database.
    * added scripts to show how to test the API with https://github.com/AnWeber/vscode-httpyac[httpyac] and Bruno.
- `monitoring`: Add monitoring to the app.
    * At first we'll have the app export metrics to https://prometheus.io/[Prometheus]
    

== Developement
In general i'll stick to building the API in a TDD way. Tests are written in https://docs.pytest.org/en/stable/[pytest].

== Project Links
- http://localhost:8000/docs[Swagger UI]
- http://localhost:8000/redoc[ReDoc]
- http://localhost:8010/?pgsql=startrek_db&username=star&db=star-trek-db&ns=public[DB Adminer]

== General Links
- https://www.youtube.com/@ArjanCodes[@ArjanCodes] is a great channel to learn about FastAPI and Python in general.
- https://fastapi.tiangolo.com/[fastapi.tiangolo.com] is the official documentation for FastAPI.
- https://www.usebruno.com[Bruno] makes a fine replacement for Postman, Insomnia and other API testing tools.

== ToDos
- https://www.freecodecamp.org/news/how-to-run-github-actions-locally/s[Test Guhub Actions locally] w act
