= FastAPI - One Stop Shop

We will be building a full blown REST API based on FastAPI.
We'll start with a simple API and then add more features to it.
This will be a simple API that will allow us to create, read, update and delete data on ships from the Startrek universe.

Everything will be done in devcontainers. So you can run the code in a container without having to install anything on your local machine - except Docker Desktop.

== Branching

I'll split the implementation into multiple parts. Each part in its own branch - so you can skip any part you don't want to see.
The branches will be named after the part they represent.
The branches are:

- `phase-0`: Basic FastAPI app with all dependencies, a simple GET endpoint and test code. A Makefile is included to show how to run the tests and stuff. A Pipeline is included to run the tests on every commit. Coverage reports are generated and published to https://cwacoderwithattitude.github.io/articles_dc_fastapi_startrek/[github pages].

== Developement
In general i'll stick to building the API in a TDD way. Tests are written in https://docs.pytest.org/en/stable/[pytest].

== Links
- https://www.youtube.com/@ArjanCodes[@ArjanCodes] is a great channel to learn about FastAPI and Python in general.
- https://fastapi.tiangolo.com/[fastapi.tiangolo.com] is the official documentation for FastAPI.