services:
  articles_dc_fastapi_startrek:
    container_name: articles_dc_fastapi_startrek
    hostname: articles_dc_fastapi_startrek.local
    env_file:
      - .env
    build:
      context: .
    working_dir: /src
    volumes:
      - ..:/src:cached
    command: >
      bash -c "sleep infinity"
    ports:
      - "${app_port}:8000"
    networks:
      articles_dc_fastapi_startrek-net:

      
networks:
  articles_dc_fastapi_startrek-net:
