services:
  articles_dc_fastapi_startrek:
    container_name: articles_dc_fastapi_startrek
    hostname: articles_dc_fastapi_startrek.local
    env_file:
      - .env
    build:
      context: .
    working_dir: /src
    volumes:
      - ..:/src:cached
    command: >
      bash -c "sleep infinity"
    ports:
      - "${app_port}:8000"
      - "${nicegui_port}:8080"
    depends_on:
      - startrek_db
    networks:
      articles_dc_fastapi_startrek-net:
  dc_spring_boot:
    image: mcr.microsoft.com/devcontainers/java:17
    volumes:
      -  ..:/src:cached
      -  $HOME/.m2:/home/vscode/.m2:cached
    working_dir: /src/spring_boot
    container_name: dc_spring_boot
    ports:
      - "8088:8080"
    #depends_on:
    #  - startrek_db
    command: >
      bash -c "sleep infinity"
    networks:
      articles_dc_fastapi_startrek-net:
  startrek_db:
  #image: postgres:17.4-alpine3.21
    image: postgres:14.1-alpine
    container_name: startrek_db
    restart: always
    environment:
      - POSTGRES_USER=${db_user}
      - POSTGRES_PASSWORD=${db_password}
      - POSTGRES_DB=${db_name}
    ports:
      - "${db_ext_port}:5432"
    networks:
      articles_dc_fastapi_startrek-net:
    volumes:
     - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer:5.0.4
    container_name: adminer
    restart: always
    ports:
      - ${adminer_port}:8080
    depends_on:
      - startrek_db
    networks:
      articles_dc_fastapi_startrek-net:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus.local
    ports:
      - ${prometheus_port}:9090
    volumes:
      - ./prometheus_config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_config/alert_rules.yml:/etc/prometheus/alert_rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    networks:
      articles_dc_fastapi_startrek-net:

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - ${grafana_port}:3000
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
       - prometheus
    networks:
      articles_dc_fastapi_startrek-net:

  alertmanager:
    image: prom/alertmanager:latest
    restart: unless-stopped
    container_name: alertmgr
    hostname: alertmanager.local
    environment:
      - ALERTMANAGER_SMTP_REQUIRE_TLS=false
    ports:
      - ${alertmanager_port}:9093
    volumes:
      - "./alertmanager:/config"
      - alertmanager-data:/data
    command: --config.file=/config/alertmanager.yml --log.level=debug
    networks:
      articles_dc_fastapi_startrek-net:
      
  # https://github.com/dockage/mailcatcher
  mailcatcher:
    restart: on-failure
    image: dockage/mailcatcher:0.9.0
    hostname: mailcatcher.local
    ports:
    - "1080:1080"
    - "1025:1025"
    networks:
      articles_dc_fastapi_startrek-net:

networks:
  articles_dc_fastapi_startrek-net:

volumes:
  db_data: 
    driver: local
  grafana_data:
    driver: local
  alertmanager-data:
    driver: local
  data:
    name: kener_db
